name: Build

on: 
  push:
  workflow_dispatch:

env:
  TOOLCHAIN: cruel
  INSTALLER: yes
  # FORCE GitHub to use the 2026 standard for Node
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true 

jobs:
  build:
    # Switching to 20.04 often helps legacy kernel toolchains 
    # that are picky about library versions.
    runs-on: ubuntu-20.04 

    strategy:
      fail-fast: false
      matrix:
        model: [ "G970F,G973F,G975F", "N975F" ]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo apt-get install -y -qq libtinfo5 libncurses5 ccache
