name: Build

on: 
  push:
  workflow_dispatch:

env:
  TOOLCHAIN: cruel
  INSTALLER: yes
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true 

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        model: [ "G970F,G973F,G975F" ]

    steps:
      - uses: actions/checkout@v4
      
      - name: Install Legacy Libraries
        run: |
          sudo apt-get update
          wget http://security.ubuntu.com/ubuntu/pool/universe/n/ncurses/libtinfo5_6.3-2ubuntu0.1_amd64.deb
          sudo apt install ./libtinfo5_6.3-2ubuntu0.1_amd64.deb
          sudo apt-get install -y -qq libncurses5 ccache

      - name: Surgical Magisk Bypass
        run: |
          # This finds the exact line causing the FileNotFoundError and disables it
          sed -i 's/update_magisk(configs\[.kernel.\]\[.magisk.\].get(.version.))/pass/g' ./cruelbuild

      - name: Kernel Configure
        run: |
          set -e -o pipefail
          ./cruelbuild config                   \
                       model=${{ matrix.model }} \
                       name="Cruel-devel"        \
                       toolchain=$TOOLCHAIN      \
                       +magisk                   \
                       +nohardening              \
                       +ttl                      \
                       +wireguard                \
                       +morosound                \
          2>&1 | tee config.info

      - name: Deploy Toolchain
        run: git clone --depth 1 -j $(nproc) --branch $TOOLCHAIN --single-branch https://github.com/CruelKernel/samsung-exynos9820-toolchain toolchain

      - name: Kernel Build
        run: ./cruelbuild :build

      - name: Install Build Tools
        run: |
          wget -q https://android.googlesource.com/platform/system/tools/mkbootimg/+archive/refs/heads/master.tar.gz -O - | tar xzf - mkbootimg.py gki
          chmod +x mkbootimg.py
          sudo mv mkbootimg.py /usr/local/bin/mkbootimg
          sudo mv gki $(python -c 'import site; print(site.getsitepackages()[0])')
          wget -q https://android.googlesource.com/platform/external/avb/+archive/refs/heads/master.tar.gz -O - | tar xzf - avbtool.py
          chmod +x avbtool.py
          sudo mv avbtool.py /usr/local/bin/avbtool

      - name: Create CruelKernel images
        run: ./cruelbuild :mkimg
      
      - name: Create CruelKernel installer
        if: env.INSTALLER == 'yes'
        run: ./cruelbuild :pack

      - name: Upload Kernel Zip
        if: env.INSTALLER == 'yes'
        uses: actions/upload-artifact@v4
        with:
          name: CruelKernel-S10-Series
          path: CruelKernel.zip
